### ISSUE TITLE
please update build environment for node 0.10

### ISSUE THREAD

**Issue by seebi** [0xfeedface/node_raptor#8]
this includes at least the usage of node-gyp

**Comment by seebi** [comment]
I've done this:

```
node-gyp clean configure build install
```

however, after starting `node_ldp::bin/start` I've got 

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol bindings_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/raptor/index.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by 0xfeedface** [comment]
Node-gyp will not install it as a node module; it is only used for building. Please use `npm install -g`.

**Comment by seebi** [comment]
ok, thanks - will update the readme. do you want to move node_raptor to /AKSW ?

**Comment by 0xfeedface** [comment]
I have not yet decided on whether to support pre 0.8 Node environments. That's why the `wscript` is still there and `Makefile` and read me have not been updated yet.

No, I would like to keep some side projects of my own. But you are welcome to clone it. :)
